stages:
  - deploy

deploy:
  stage: deploy
  image: ruby:2.7
  before_script:
    - apt-get update -y && apt-get install -y lftp
  script:
    - lftp -c "set ftp:list-options -a;
               set ssl:verify-certificate no;
               open ftp://$FTP_USER:$FTP_PASS@$FTP_HOST;
               mirror -R --parallel=10 --delete ./ $FTP_PATH;"
  only:
    - main
