stages:
  - build
  - deploy

build:
  stage: build
  image: node:alpine
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - public/build

deploy:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache lftp
  script:
    - lftp -c "set ftp:list-options -a;
               set ssl:verify-certificate no;
               open ftp://$FTP_USER:$FTP_PASS@$FTP_HOST;
               mirror -R --parallel=5 --delete --exclude-glob .env --exclude-glob .htaccess ./ $FTP_PATH;"
  dependencies:
    - build
  only:
    - master
